### ISSUE TITLE
yield to signal

### ISSUE THREAD

**Issue by ghost** [neikeq/GodotSharp#10]
Will there be an equivalent of [yielding to signal](http://docs.godotengine.org/en/latest/reference/gdscript.html#coroutines-signals) as in gdscript? I believe it works different than ordinary yield in C#.

I'm mainly trying to understand whether C# will provide a workaround for [this issue](https://github.com/godotengine/godot/issues/3235) or not.

**Comment by neikeq** [comment]
In that issue you wrote this:

> make a yield-like function (let's call it `wait`), which behaves like yield, except when the signal handler completes, in jumps to the line right after `wait` is called (rather than yielding the control to the parent function in the GDScript call stack).

Did you mean something like [`async` and `await`](https://msdn.microsoft.com/en-us/library/mt674882.aspx)?

**Comment by olsonjeffery** [comment]
Would have to provide a custom TaskScheduler wired up to Godot's main loop
but yeah pretty much this.

**Comment by olsonjeffery** [comment]
Would also imply making most if not of godot's api surface async or at
least the calls which have corresponding signals tied to them (or a
parallel non blocking API)

**Comment by ghost** [comment]
I do know about async and await in C#, but I'm not sure how/whether they can work with or as godot's yield-to-signal since they work in different ways.

As you know, with yield-to-signal, the current function pauses and execution continues running from the upper function in the call stack, and the execution is resumed automagically after _gdscript runtime_ calls the signal handler function and the signal is handled. On the other hand, async/await allows us to wait for an asynchronous function that _we_ called. (It also doesn't pause the current function like yield in either situation, although I personally don't like this "feature" or lua-like coroutines anyway, which feels like a crippled and hardly useful version of CSP.)

So could you please clarify how exactly you mean to use async/await with/for yield-to-signal?

**Comment by ghost** [comment]
In the original context of gdscript, I merely meant one could add a new function, let's say `wait`, which is similar to yield-to-signal, except it "waits" until the signal handler completes (and maybe return the value that is returned from the signal handler). In certain aspects, it is similar to `await` in C# (they both allow us to wait for some task to complete), but there are differences too (`await` waits for an asynchronous task we started whereas `wait` would wait for a (synchronous) signal that will be exectuted by the runtime at some point in the future), and I'm not sure how I can reconcile them.

**Comment by neikeq** [comment]
I meant something like this (based on your example):

``` C#

async void talk()
{
    var color = await questional_modal(
            "What color do you like",
            new [] { "Red", "Blue", "Green" }
    ); // if `question_modal` did not complete, we also yield to our caller
    
    // resumed when `question_modal` completed
    if (color == 0)
    // and so on...
}

object m_param;

async object questional_modal(string question, string[] answers)
{
     // stuff...
    await WaitSignalAsync(node, "button_selected"); // yields control back to `talk`
    
    // resumed when the signal is emitted, just like with GDScript's yield on signal
    // more stuff here...
    return m_param;
}

void _on_button_selected(object param)
{
    m_param = param;
}
```

Is this what you want?

**Comment by ghost** [comment]
So `color` is determined by `return m_param` in `questional_modal`, right?

Yes, I think this would work (unless I'm misunderstanding how await works). `WaitSignalAsync` doesn't exist yet though, right?

**Comment by neikeq** [comment]
Done in 9e362d6 ([example code snippet here](https://github.com/neikeq/GodotSharp/issues/8#issuecomment-315611365))
