### ISSUE TITLE
Make C# methods callable via Object.call too

### ISSUE THREAD

**Issue by karroffel** [neikeq/GodotSharp#14]
It's possible to call methods in other scripting langauges with the Object API. But it's not possible to do that with a C# script.

Example: I'm writing a level loading system, I want the game to be moddable so GDScript should be supported -> Object.call(). I can't use the same interface to use levels scripted in C# though.

**Comment by karroffel** [comment]
It's also not possible to connect to signals on `this` because of this.

(like `level.connect("level_loaded", this, "level_loaded")` )

**Comment by neikeq** [comment]
I swear this was possible. I even used this to test variant and varargs.

Just to be sure, what is not working? C# -> C#, C# -> GDScript or GDScript -> C#?

**Comment by neikeq** [comment]
I just tested the following and it worked:

``` C#
using GodotEngine;

class Test
{
    Vector2 get_pos_plz(string a)
    {
        Godot.print(a);
        return get_pos();
    }

    void hello_there()
    {
        Godot.print("Hello, " + get_name() + "!");
    }

    void _ready()
    {
        Godot.print(call("get_pos_plz", "ok thx"));
        connect("renamed", this, "hello_there");
        set_name("NotPlayer");
    }
}
```

Output:

```
ok thx
(0, 0)
Hello, NotPlayer!
```

**Comment by karroffel** [comment]
Maybe I just did something wrong... Will try later 😄

**Comment by karroffel** [comment]
Project in which I'm trying to use it. Try switching the script from C# to GDScript in the test.tscn scene.

[godotjam_dec2016.zip](https://github.com/neikeq/GodotSharp/files/671412/godotjam_dec2016.zip)

**Comment by karroffel** [comment]
So sorry for bothering, I should've checked the naming twice. ☹️
