### ISSUE TITLE
Error when building Godot.

### ISSUE THREAD

**Issue by asusralis** [neikeq/GodotSharp#26]
[Initial build] Compiling ==> modules\mono\build_config.cpp
build_config.cpp
[Initial build] Compiling ==> modules\mono\csharp_script.cpp
csharp_script.cpp
[Initial build] Compiling ==> modules\mono\il_opcode_parser.cpp
il_opcode_parser.cpp
modules\mono\il_opcode_parser.cpp(51): error C2131: expression did not evaluate to a constant
modules\mono\il_opcode_parser.cpp(51): note: failure was caused by a read of a variable outside its lifetime
modules\mono\il_opcode_parser.cpp(51): note: see usage of 'p_locals'
modules\mono\il_opcode_parser.cpp(62): error C2131: expression did not evaluate to a constant
modules\mono\il_opcode_parser.cpp(62): note: failure was caused by a read of a variable outside its lifetime
modules\mono\il_opcode_parser.cpp(62): note: see usage of 'max_size'
scons: *** [modules\mono\il_opcode_parser.windows.tools.64.obj] Error 2
scons: building terminated because of errors.

Not sure what I did wrong. I'm using the latest source from both godot and godotsharp.

**Comment by neikeq** [comment]
This file is not needed for now, so you can remove or `#if 0` it.

**Comment by asusralis** [comment]
Wow, fast reply! Removing the files worked for that part, but I got another error much later on in the build process. *I think* it's related to godotsharp, but correct me if I'm wrong.

[Initial build] Linking Static Library ==> modules\freetype\freetype_builtin.windows.tools.64.lib
[Initial build] Linking Program        ==> bin\godot.windows.tools.64.exe
LINK : fatal error LNK1181: cannot open input file 'monosgen-2.0.lib'
scons: *** [bin\godot.windows.tools.64.exe] Error 1181
scons: building terminated because of errors.

**Comment by neikeq** [comment]
I guess you forgot to set the environment variable for the mono installation directory, [as explained here](https://github.com/neikeq/GodotSharp/wiki/Building#windows-variables), and it's trying with `%PROGRAMW6432%\Mono` by default, which probably does not exist.

Try running scons with `verbose=yes` to find out.

**Comment by asusralis** [comment]
I think it is set to the right directory: http://i.imgur.com/AKbpIPq.png

After looking around in my mono directory, I cannot seem to find monosgen-2.0.lib in mono/lib. I can, however, find mono-2.0-sgen.lib. I installed mono for 32-bit and it's the same way. I'm not sure why I don't have monosgen-2.0.lib, but downloading mono again does not help this problem.

If it helps - windows 10 x64 with the latest mono release (5.2.0.215).

**Comment by neikeq** [comment]
Looks like the file was renamed.

**Comment by asusralis** [comment]
Oh, I see. Is there something I can change so it can build?

**Comment by neikeq** [comment]
Could you check if it's fixed now?

**Comment by asusralis** [comment]
It builds (yay!), but when I try to run the binary it throws an error because mono-2.0-sgen.dll was not found.

**Comment by neikeq** [comment]
Ah, right. Can't believe I forgot to mention this in the build steps. You must place this dll in the same directory as your executable. I think you can find it in the same directory as the lib.

**Comment by asusralis** [comment]
It starts but then throws an error -
 Assembly Loader probing location: 'C:\Users\XXX\Documents\GodotSource\lib\mono\4.5\mscorlib.dll'.
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `C:\Users\XXX\Documents\GodotSource\lib\mono\4.5\mscorlib.dll' directory.

I've created that directory - which didn't exist -  and added my mscorlib.dll found in my mono installation directory, but it says it is an invalid CIL image. Was I supposed to create that directory beforehand?

**Comment by neikeq** [comment]
No idea why it's trying to load it from `C:\Users\XXX\Documents\GodotSource` instead of the mono installation directory.
Does it make any difference if you place `mono_set_dirs(NULL, NULL);` at the beginning of `GDMono::initialize`?

https://github.com/neikeq/GodotSharp/blob/3171be303aeeec380ed2fb0aea8c49468d326179/mono/mono_wrapper/gd_mono.cpp#L44-L46

**Comment by asusralis** [comment]
My GDMono::initialize looks like this now: 
```
void GDMono::initialize() {
	mono_set_dirs(NULL, NULL);

	OS::get_singleton()->print("Initializing mono...\n");
```

It's still looking for mscorlib.dll in my godotsource directory. :( I accidentally left out one line that it prints after "Initializing mono..." when trying to start Godot. Not sure if it means anything:

Initializing mono...
Mono: Config attempting to parse: ' '.

**Comment by asusralis** [comment]
So... after many, many errors, I finally got it to work. I manually made the directory and copied the correct mscorlib. 

The terminal keeps printing errors/warnings, but everything seems to be working, so I'm just going to ignore them and focus on playing with GodotSource.

Thanks for helping.

**Comment by neikeq** [comment]
This is still a bug though. You shouldn't need to do this. I will test it soon on Windows.

**Comment by neikeq** [comment]
The last bug is fixed now. Now we detect the mono installation directory from the windows registry in tool and debug builds. Release builds don't need this because they will be self contained.
