### ISSUE TITLE
Error: Failed to build API solution

### ISSUE THREAD

**Issue by NathanWarden** [neikeq/GodotSharp#33]
It looks like a lot of work has been done to improve the usability of C# in Godot! :)

When I try to run a project now I get the following error: "Failed to build API solution". Does anybody know what I'm doing wrong? Do I still need to tell Godot to generate a csharp project and all that stuff still before it'll work? I've done that and it doesn't seem to make a difference. It looks like it's all supposed to auto-generate via the .mono folder.

Thanks for any help! :)

**Comment by BrainBlasted** [comment]
You still need to generate glue, if you haven't. The command is changed 
to --generate-mono-glue now. Otherwise, your code itself likely has 
errors. If you're using an external editor, you can set that in the 
Editor Settings menu so it integrates/autocompletes properly.

**Comment by neikeq** [comment]
What are the build errors? You can find them in `Mono (bottom panel) > Builds > Core API [Release]`.

**Comment by NathanWarden** [comment]
@BrainBlasted Thanks for the suggestion as I didn't realize this flag had changed. This doesn't seem to be the problem however, but might have bit me in the future. :)

@neikeq Thanks, I didn't see the 'Mono' section of that panel before. Nice to know about, thanks. I have three errors:

1) AudioStreamPlayer.cs(125,21): The type 'AudioStreamPlayer' already contains a definition for Play
2) AudioStreamPlayer2D & 3D have the same error.

Looking at the csproj, sure enough 'Play' is defined twice, once as a property and also as a method. This is from 'AudioStreamPlayer.cs':

```
public bool Play
{
     get
     {
          return _IsActive();
     }
     set
     {
          _SetPlaying(value);
     }
}
```

and

```
[GodotMethod("play")]
public void Play(float fromPos = 0f)`
{
    NativeCalls.godot_icall_1_10(method_bind_4, Object.GetPtr(this), fromPos);
}
```

**Comment by NathanWarden** [comment]
This seems more like an issue to open with Godot. It doesn't make sense to have a method named play and a property named play.

**Comment by NathanWarden** [comment]
Opened a pull request for this for Godot: https://github.com/godotengine/godot/pull/11211
