### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by SquishyMucus** [neikeq/GodotSharp#40]
I'm following the linux example changing names where necessary. I have gotten to the glue stage.
"bin/godot.windows.tools.64 --generate-mono-glue modules/mono/glue"

I'm getting a whole bunch of errrs and warnings.

C:\godot> bin\godot.windows.tools.64.exe --generate-mono-glue modules/mono/glue
Couldn't open C:\godot\bin/godot.windows.tools.64.pck
Couldn't open godot.windows.tools.64.pck
Couldn't load/find C:/godot/project.godot or project.binary
Couldn't load/find C://project.godot or project.binary
Activated GL 3.3 contextOpenGL ES 3.0 Renderer: AMD Radeon HD 6800 Series
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
WARNING: not found: gdnative/singletons
Initializing mono...
Mono: Runtime initialized
Mono: EVERYTHING OK
WARNING: BindingsGenerator::_populate_object_type_interfaces: Name of method `Popup` is ambiguous with the name of its class `Popup`. Renaming method to `Popup_`
     At: modules\mono\editor\bindings_generator.cpp:1640
WARNING: BindingsGenerator::_populate_object_type_interfaces: Name of method `Reference` is ambiguous with the name of its class `Reference`. Renaming method to `Reference_`
     At: modules\mono\editor\bindings_generator.cpp:1640
Generating ARVRAnchor...
Generating ARVRCamera...
Generating ARVRController...
*** lots more generating goes here ***
Generating _Thread...
ERROR: No loader found for resource: res://modules/mono/glue
   At: core\io\resource_loader.cpp:184
ERROR: Failed loading scene: res://modules/mono/glue
   At: main\main.cpp:1515
Mono: Runtime cleanup...
debugger-agent: Unable to listen on 5576
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:1858

If I ignore all those and build:
"scons p=windows target=release_debug tools=yes"
I build and run the application fine.

The problem comes the moment I try and add a c# script.
The whole app hangs on 'Generating solution' and 'building GodotSharp solution', I get no errors in the debug window.

**Comment by BrainBlasted** [comment]
The errors/warnings at the end are normal. How long do you wait for it to build solutions?

**Comment by NathanWarden** [comment]
> The problem comes the moment I try and add a c# script.
> The whole app hangs on 'Generating solution' and 'building GodotSharp solution', I get no errors in the debug window.

I have problems with it hanging in Windows too. The binary of build of Godot with GodotSharp itself is fine, but when in the editor hitting F5/F6 does the same as what you've described. Linux works fine though. I'm rebuilding with the latest Godot and GodotSharp right now and will report back if I can get a csharp solution to compile.

**Comment by SquishyMucus** [comment]
I've left it alone for about an hour while I had dinner, no change.

I can also reproduce the F5 problem. If I kill the process on script creation and reopen godot the script is sometimes there. if I then click run, it hangs.

I'm also using VS2017.

**Comment by neikeq** [comment]
No idea why this happens on Windows. However, blocking the main thread while building is not a good idea in the first place. The reason for it to be this way is because `EditorNode`'s build callback is not asynchronous, so I guess that needs to be changed.

**Comment by SquishyMucus** [comment]
So is it a fair assumption that a windows build is a no-go for now ?

**Comment by NathanWarden** [comment]
@nobnob2015 I think so, I'm still having the same issue where it's just stuck on "Building Godot Sharp solution..." indefinitely.

There are no errors in the x64 native tools command prompt either.

**Comment by neikeq** [comment]
Alright, the problem is that we redirect stdout and stderr from the msbuild process and if the buffer is full it will block trying to write to it. I'll fix it tonight.

**Comment by neikeq** [comment]
Does this still happen after 03294a8?

There was also the issue of `AssemblyInfo.cs` being added to the project with slash instead of backslash as path separator, which apparently MSBuild does not like on Windows. If there is a build error related to this file not being found, delete the solutions in `%appdata%\Godot\mono\solutions\` and replace `Properties/AssemblyInfo.cs` with `Properties\AssemblyInfo.cs` in your project's csproj (or just delete the solution so it can be regenerated).

**Comment by NathanWarden** [comment]
Unfortunately it's still happening as of the latest commit.

**Comment by SquishyMucus** [comment]
Seems to build and compile/run fine for me now. Will play some more with it this evening.

**Comment by SquishyMucus** [comment]
Problem now is that none of the code I add ever gets hit, it's like the script doesn't get loaded. Breakpoints don't get hit either (should I open a new bug for this)

**Comment by neikeq** [comment]
Yes, and include an example project if possible.

**Comment by SquishyMucus** [comment]
There was nothing special about the project. I just create a new project in godot, add a 2d node, attach a c# script to that node. No code in the ready function gets called or stopped on using breakpoints.

**Comment by NathanWarden** [comment]
I finally got it to compile. :) But, it doesn't run any of the code. :(

Here's a minimal project with only ready and process methods overridden. Neither call their code.
[GodotMonoExample.zip](https://github.com/neikeq/GodotSharp/files/1321677/GodotMonoExample.zip)

**Comment by SquishyMucus** [comment]
What might be relevant is that if I open the basic project in visual studio, it tries to reference GodotSharpEditor.dll which does not exist.

**Comment by SquishyMucus** [comment]
Ok I was able to get the node to use the c# script. What you need to do is, after you add a node, name it something unique then when attaching a script make sure the script has the same name as the node that you just created (the class name doesn't matter as long as the script name and node name are the same).

Now to figure out inheritance ... :)

**Comment by neikeq** [comment]
@NathanWarden Your example works fine for me. Could it be that you are using a build with `mono_glue=no`?

@nobnob2015 Yes, the file name must be the same as the class name. I'll add a warning later to make this is less confusing.

**Comment by NathanWarden** [comment]
@neikeq I'll double check. I make my build for this via a bat file, so I'll run the commands manually this time just to be sure since bat files do tend to be far more finicky than Linux shell scripts.

**Comment by NathanWarden** [comment]
@neikeq Yep, it was my batch file didn't execute the second build command. In other words, everything is good here after I manually built :)

**Comment by SquishyMucus** [comment]
@NathanWarden Are you able to debug any of the code?

**Comment by NathanWarden** [comment]
No, but I'm not sure debugging is even implemented. If you need some sort of feedback from your code you can always use: GD.print(whatever);

I've played quite a bit already with GodotSharp on Linux, but I haven't tried using breakpoints or anything like that. I'm pretty sure Godot would have to actually attach itself to the debugger, and not just open the IDE by double clicking the file. I'm sure @neikeq could clarify whether or not this should be possible yet. I'm going to make a wild guess and say it isn't.

Regardless, I'm happy it's working on Windows. Thanks @neikeq for your help :)

**Comment by neikeq** [comment]
The plan is to create debugging extensions for VS Code, MonoDevelop and Visual Studio.
If you don't want to wait, the [Mono Debug](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug) extension for VS Code is working fine for me, it just requires some manual configuration.

**Comment by SquishyMucus** [comment]
That sounds great, would you be able to share that configuration

**Comment by neikeq** [comment]
This is my _launch.json_:

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach",
            "type": "mono",
            "request": "attach",
            "address": "localhost",
            "port": 23685
        }
    ]
}
```

**Comment by SquishyMucus** [comment]
What did you have to do within godot to get it to start debugging on port 23685, I can't find any settings that specify debug ports

**Comment by SquishyMucus** [comment]
I have also tried changing port to 6007. I then run the game, attach the debugger in VScode.
None of the breakpoints get hit but if I stop the game the debugger automatically stops in VSCode  so it seems there is some sort of a connection.

**Comment by neikeq** [comment]
I added some project settings in 4d9ec0a to configure some of the debugger agent options, specially `mono/debugger_agent/port`. I fixed the editor as well, which was already listening on that port.
