### ISSUE TITLE
Unable to build android export templates

### ISSUE THREAD

**Issue by SquishyMucus** [neikeq/GodotSharp#42]
build of android export templates fails. I'm running the following after I have created a fully functioning godot app (ie: after following godotsharp build instructions).

command:
     `scons platform=android tools=no target=release_debug
`
error:
     `[ 11%]  Compiling ==> mmodules\mono\csharp_script.cpp
     csharp_script.cpp
     modules\mono\csharp_script.cpp(482): error C2039: 'exports_invalidated': is not a member of 
     'CSharpScript'
     c:\godot\modules\mono\csharp_script.h(61): note: see declaration of 'CSharpScript'
     scons: *** [modules\mono\csharp_script.windows.opt.debug.64.obj] Error 2
     cons: building terminated because of errors.
`

**Comment by neikeq** [comment]
I didn't try building for android and iOS yet because exporting is not working. Godot's ExportPlugin was just added back last weekend so I didn't start to work on it yet. It will be done after alpha2.

That build error was fixed by 7aa4a40 though.

**Comment by SquishyMucus** [comment]
Thanks, will wait.
