### ISSUE TITLE
TextureImage or Image not created properly?

### ISSUE THREAD

**Issue by NathanWarden** [neikeq/GodotSharp#47]
When creating an Image and ImageTexture dynamically through code, the example project only works in GDScript and not C#.

I could be wrong, but I think the real issue might be that the texture doesn't actually get created internally via whatever the "ImageTexture.new()" or "Image.new()" do in GDScript. I've also tried using the "Call" method on each item instead of calling it directly. IE. I've used "dynImage.Call("create",256,256,false,Image.FORMAT_RGB8);" instead of "dynImage.Create(256,256,false,Image.FORMAT_RGB8);" If done in GDScript they work as expected. I'm not sure if they work properly in C# though as, again, I'm not sure the image or texture are created properly via the equivalent "new()" function from GDScript.

What should happen in this example is that there should be two red textures created, one in GDScript and the other in C#. Only the GDScript one works, however.

[TextureBug.zip](https://github.com/neikeq/GodotSharp/files/1330994/TextureBug.zip)

I'll add more below if I find out more.

**Comment by NathanWarden** [comment]
Note: Please also ignore the comments "// This doesn't work" as I'm no longer convinced that these are necessarily the exact lines causing the issue(s).

**Comment by NathanWarden** [comment]
Okay, I'm not sure this is important to finding the bug, but it looks like "GDNativeClass::_new()" isn't (and can't be) called from C#, whereas it is the required way to create a new instance of an Object in GDScript.

IE: In GDScript the following won't create a node, image, texture, etc:
    `var node = Node # equivalent of var node = new Node() in C#`
but instead must call:
    `var node = Node.new()`
or in this precise case:
    `var image = Image.new() # GDScript`
and is not doing the same thing as:
    `Image image = new Image(); // C#`

Again, I don't know if this is the issue, but just trying to work though it in hopes it will save time for someone else :)

**Comment by neikeq** [comment]
Seems to be a problem with ptrcall, the image instance is passed correctly to it, but `ImageTexture::create_from_image` receives a null reference.

**Comment by neikeq** [comment]
Oh, nevermind. This is a known issue that I forgot to fix. When the managed side is the only one holding the reference alive, but then the reference is passed again to native, the atomic reference will fail because it's already 0. I'll have to discuss this with @reduz

**Comment by NathanWarden** [comment]
Cool, thanks :)

**Comment by neikeq** [comment]
All right, refcounting should be working fine after 8863201

BTW, there is a leak in your GDScript. If you run `godot --path /path/to/TextureBug -v` (with `-v` for verbose output), you will see a message at exit telling you an `ImageTexture` was not freed. Commenting the following line fixes it: `print("GDScript tex on TextureRect: " + var2str(self.texture == imageTexture))`. Not sure why this happens, so it may be worth reporting.

**Comment by NathanWarden** [comment]
Awesome! Yep it's working!

I definitely didn't notice the leak. I'll report it to the main Godot repo.

Thanks again :)

**Comment by NathanWarden** [comment]
Hmmm, can't reproduce that message even when running multiple times (both Godot itself and player via F5/F6) with the -v flag. Maybe it got fixed recently or has something to do with a system library?

I'm sure if it's really a problem it'll show up again ;)
