### ISSUE TITLE
Godot failed to build solution on windows because of Rect3.cs

### ISSUE THREAD

**Issue by MadIcecream** [neikeq/GodotSharp#51]
The error log is Rect3.cs(104, 59): the nameof doesnt exist.

**Comment by neikeq** [comment]
It was using .NET FW's msbuild on Windows, and yours does not seem to support C# 6. I just added an option to select the build tool in editor settings (_"mono/builds/build_tool"_). The default one is [Mono's msbuild](http://www.mono-project.com/docs/about-mono/releases/5.0.0/#msbuild ).

**Comment by neikeq** [comment]
BTW, I have [this issue](https://bugzilla.xamarin.com/show_bug.cgi?id=59143) with Mono's msbuild on Windows 7 x64. If you get the same problem, switch the option to _xbuild_ for now.

**Comment by MadIcecream** [comment]
Now my build is 162dbdc1744105bccb261c9bec016950ada821c6 with 4f39ce3 of godot.
On win7 x64, I have that issue too with mono msbuild, but xbuild cannot build neither.
xbuild just told me failed to build, the log is blank.
If I `xbuild /p:Configuration=Release GodotSharp.sln` from cmd, the error log is `CSC: error CS0041: Unexpected error writing debug information -- 'The ve
rsion of Windows PDB writer is older than required: 'diasymreader.dll''`
BTW, `xbuild /p:Configuration=Debug GodotSharp.sln` succeed, though godot doesnt seem to want the debug version binary.

**Comment by MadIcecream** [comment]
And I think I found why I cannot build solution with .net msbuild.
Godot doesn't get the path to the MOST RECENT msbuild since it gets the path from "SOFTWARE\\Microsoft\\MSBuild\\ToolsVersions\\4.0"
Maybe we should try this method: https://gist.github.com/jpluimers/9b9953050aab8e3e511f

**Comment by neikeq** [comment]
Oh, right. It should be 14.0 not 4.0. It needs to check vswhere as well.

**Comment by neikeq** [comment]
Should be working after 254d011

**Comment by MadIcecream** [comment]
Still cannot work, the log just said it throw an error.

**Comment by neikeq** [comment]
If you hover that log it should show a tooltip with the exception message.

**Comment by MadIcecream** [comment]
![qq 20170930211304](https://user-images.githubusercontent.com/3340057/31046035-3304cba8-a624-11e7-94f0-f4b3838ffeff.png)
It's too long to show....
Those chinese words means "System cannot find the file specified"

**Comment by neikeq** [comment]
This is fixed on master. I wish tooltips were smarter about that.
