### ISSUE TITLE
Built-in types and global scope methods and constants

### ISSUE THREAD

**Issue by neikeq** [neikeq/GodotSharp#6]
There is no global scope in .NET so those methods and constants will be implemented in classes. Check the [the list of API differences](https://github.com/neikeq/GodotSharp/wiki/API-Differences).

Progress on built-in types:
- [x] AABB
- [x] Array
- [x] Color
- [x] ColorArray
- [x] Dictionary
- [x] Error
- [x] Image
- [x] InputEvent
- [x] InputEventAction
- [x] InputEventJoystickButton
- [x] InputEventJoystickMotion
- [x] InputEventKey
- [x] InputEventMouseButton
- [x] InputEventMouseMotion
- [x] InputEventScreenDrag
- [x] InputEventScreenTouch
- [x] IntArray
- [x] Matrix3
- [x] Matrix32
- [x] NodePath
- [x] Plane
- [x] Quat
- [x] RID
- [x] RawArray
- [x] RealArray
- [x] Rect2
- [x] String
  - Add extension methods for Godot's String methods missing in System.String.
- [x] StringArray
- [x] Transform
- [x] Variant (System.Object)
- [x] Vector2
- [x] Vector2Array
- [x] Vector3
- [x] Vector3Array

Some of these types may be unnecessary or implemented in a different way.

**Comment by kubecz3k** [comment]
I'm wondering do you have already  plans on how you will implement Arrays? My main concern with arrays is the fact that resizing them will cause GC so it will be very bad idea to do this kind of stuff inside game loop. From the other side using methods like append() is very easy and pleasant. Previously I was programming with java game library LibGDX, which have successfully (in my opinion) found a middle ground. In general in LibGDX when you wanted to use array which can modify its content dynamically you were able to create array which had some amount of items 'in reserve'. 
Like you could define array which could allocate 100 entries during it's creation, despite the fact  that you put only 10 items inside. Then you are able to dynamically add/remove new items without resizing array (which in java is causing GC). 
Here is LibGDX array class api: https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/utils/Array.html
And here is the implementation: https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/Array.java

**Comment by kubecz3k** [comment]
Also I have similar (but smaller since content of dictionaries is often more static) concerns when it comes to dictionaries. As I said I don't know how they work in c# but in java using those is causing GC. Because of that in libGDX they are reimplemented as well... 
LibGDX map api: https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/utils/ArrayMap.html 
LibGDX map implementation: https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/ArrayMap.java

**Comment by ghost** [comment]
@kubecz3k [List](https://msdn.microsoft.com/en-us/library/6sh2ey19%28v=vs.110%29.aspx) class in C# does this: it won't allocate until you hit the capacity, or "reserve", and you can specify the capacity in the constructor. Similar to C++ vectors.

I'm not sure how optimized Mono's implementation of [Dictionary](https://msdn.microsoft.com/en-us/library/xfhwa508.aspx) is in terms of allocations though.

**Comment by olsonjeffery** [comment]
burn that bridge when you get to it. you're a lot more likely to have your application slow because of select-n+1 problems or I/O thrashing than you are from a GC pause.

**Comment by neikeq** [comment]
Done. There may be missing some tiny bits here (specially for the possible need of extension methods for Dictionary and Arrays since we are using Dictionary\<object, object\> and List\<T\>/T[]).
