### ISSUE TITLE
Use 3.0 naming.

### ISSUE THREAD

**Issue by Marqin** [neikeq/GodotSharp#7]
It would be nice to have Godot 3.0 method names here, so C# scripts will be compatibile between 2.2 and 3.0.

**Comment by neikeq** [comment]
What type of compatibility do you mean?

AFAIK the API will change a lot in 3.0

**Comment by Marqin** [comment]
https://github.com/godotengine/godot/issues/5696 - here are listed some renames

**Comment by neikeq** [comment]
2.2 was skipped.
