### ISSUE TITLE
Properly suport async and await.

### ISSUE THREAD

**Issue by Marqin** [neikeq/GodotSharp#8]
We should properly support `async` and `await` as documented in [C# standard](https://msdn.microsoft.com/en-us/library/mt674882.aspx).

**Comment by neikeq** [comment]
What does supporting async/await concretely mean?
Should we provide a few async methods so, for example, one could `await WaitForSignalAsync("whatever_happened")`?

**Comment by Marqin** [comment]
Last time when I checked Unity, their Mono didn't have async/await support. I want Godot to use newest Mono and don't disable C# features.

Also, for async/await to be functional, Godot has to provide `SynchronizationContext` so tasks would be run on right thread and could acess game objecs/nodes.

**Comment by neikeq** [comment]
Alright, I've been doing some research and I think I get the idea of what needs to be done. Sounds pretty doable, so it will most likely happen for 3.0 - not for the alpha though which is just around the corner ;)

**Comment by neikeq** [comment]
> Last time when I checked Unity, their Mono didn't have async/await support.

I think they do provide a default SynchronizationContext now.

**Comment by neikeq** [comment]
Done in 9e362d6. Added a default SynchronizationContext and an awaitable for signals.

Example:
``` C#
async void _ready()
{
    timer.set_wait_time(5f);
    timer.start();
    await to_signal(timer, "timeout");
    Godot.print("Resumed after timeout!");
}
```

Also, similarly to GDScript's yield on signal, the return value of await after resuming is an array containing the arguments the signal was emitted with. Example:

``` C#
async void _ready()
{
    file_dialog.popup_centered();
    // object[] args = await to_signal(file_dialog, "file_selected");
    string the_file = await to_signal(file_dialog, "file_selected")[0];
    Godot.print("FileDialog selected file: ", the_file);
}
```

If there is another awaitable type (in the context of Godot) you consider would be useful, feel free to open a new issue.

**Comment by ghost** [comment]
Can an object's method wait for a signal of its own though?

I tried something like this

```cs
public class DerivedControl : Control {

private bool active;

public override void _Ready() {
    AddUserSignal("done");
    active = false;
    SetProcess(true);
}

public override void _Process(float delta) {
    if (!active) {
        return;
    }

    // do stuff
    active = false;
    EmitSignal("done");
}

public async void Test() {
    active = true;
    // wait until _Process completes whatever we're trying to do
    await ToSignal(this, "done");
}

// ...
// somewhere else, in a non-async function
GD.print("start")
derived.Test() // should block until the signal is emitted, no?
GD.print("stop")

}
```
~~but it just hangs forever when I call `Test()` in a normal way, from a non-async function.~~ nope, not this minimal example. What happens when I actually run this code is, Test() ends without waiting for `EmitSignal`. If fact you can entirely comment out `EmitSignal` and it just works the same way.

**Comment by ghost** [comment]
I probably need to start learning C#, but my understanding based on the discussion in #10 was that this should somehow work. Or does the caller also need to be `async`? (hope not because since `questional_modal`, as in the example in #10, can be called anywhere ideally, it means I need to make every single function async)

**Comment by ghost** [comment]
Just to confirm: I got this working I think, but I had to make all involved functions in the call stack async, make `Test` return a `Task` and await on that. Is this how it's supposed to be?

**Comment by NathanWarden** [comment]
I haven't used async much, but I'm pretty sure that's correct. Any method that contains 'await' must also be declared with async.

**Comment by neikeq** [comment]
Yes, code should be:

``` C#
GD.print("start")
await derived.Test()
GD.print("stop")
```

and the method should be declared async.

I recommend you to [read this](https://docs.microsoft.com/en-us/dotnet/csharp/async).

**Comment by ghost** [comment]
Yeah that's where I got the idea
